/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class bookingform extends javax.swing.JFrame {

    /**
     * Creates new form bookingform
     */
    public bookingform() throws ParseException {
        initComponents();
        //calling array from room.java
        String[] myRoom = room.myRoom;
        bookingID.setText(myRoom[0]);
        bookingLevel.setText(myRoom[1]);
        bookingSize.setText(myRoom[2]);
        //modifying jlabel attributes
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        jLabel16.setVisible(false);
        
        //calling array from booking.java
        Date[] mySearchingDate2 = booking.mySearchingDate;
        bookingStart.setDate(mySearchingDate2[0]);
        bookingEnd.setDate(mySearchingDate2[1]);
        
    }
    
    //count the number of available data to iterates throughout customer.txt
    static int countlines3() throws FileNotFoundException{
            File file = new File("Customer.txt");
            Scanner scanner = new Scanner(file);
            int count = 0;
            int line = 0;
            
            while (scanner.hasNextLine()) {
                scanner.nextLine();
                count++;
            }
            scanner.close();
            
            return count/6+1/2+1;
                   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bookingID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bookingFill = new javax.swing.JButton();
        bookingLevel = new javax.swing.JTextField();
        bookingSize = new javax.swing.JTextField();
        bookingIc = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        bookingName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        bookingEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        bookingContact = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        bookingStart = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        bookingEnd = new com.toedter.calendar.JDateChooser();
        bookingDay = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        bookingBack = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        bookingGet = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Room ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 91, -1, -1));

        bookingID.setEditable(false);
        getContentPane().add(bookingID, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 88, 131, -1));

        jLabel2.setText("Room Level: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 142, -1, -1));

        jLabel3.setText("Room Size:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 193, 68, -1));

        jLabel4.setText("IC/Passport:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 243, 68, -1));

        bookingFill.setText("Auto Fill");
        bookingFill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingFillActionPerformed(evt);
            }
        });
        getContentPane().add(bookingFill, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 239, -1, -1));

        bookingLevel.setEditable(false);
        getContentPane().add(bookingLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 139, 131, -1));

        bookingSize.setEditable(false);
        getContentPane().add(bookingSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 190, 131, -1));

        String customeric;
        RandomAccessFile raf = null;
        List<String> icPassportData = new ArrayList<>();

        try {
            raf = new RandomAccessFile("Customer.txt", "rw");

            for (int i = 1; i < countlines3(); i++) {
                // Skip reading other customer information except IC/Passport
                raf.readLine();
                customeric = raf.readLine().substring(13);
                raf.readLine();
                raf.readLine();
                raf.readLine();
                raf.readLine();
                raf.readLine();
                // Add the IC/Passport to the list
                icPassportData.add(customeric);
            }
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            if (raf != null) {
                try {
                    raf.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }

        // Create a DefaultComboBoxModel to hold the IC/Passport data
        DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();
        comboBoxModel.addElement("None");
        // Iterate over the IC/Passport numbers and add them to the ComboBoxModel
        for (String icPassport : icPassportData) {
            comboBoxModel.addElement(icPassport);
        }

        // Set the ComboBoxModel as the model for the bookingIc JComboBox
        bookingIc.setModel(comboBoxModel);
        getContentPane().add(bookingIc, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 239, 131, -1));

        jLabel5.setText("Name:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 289, 37, -1));

        bookingName.setEditable(false);
        getContentPane().add(bookingName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 131, -1));

        jLabel6.setText("Email: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 37, -1));

        bookingEmail.setEditable(false);
        getContentPane().add(bookingEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 131, -1));

        jLabel7.setText("Contact: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 58, -1));

        bookingContact.setEditable(false);
        getContentPane().add(bookingContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 131, -1));

        jLabel8.setText("Start Date: ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, -1, -1));
        getContentPane().add(bookingStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 133, -1));

        jLabel9.setText("End Date:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 59, -1));

        bookingEnd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bookingEndFocusLost(evt);
            }
        });
        bookingEnd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookingEndMouseExited(evt);
            }
        });
        bookingEnd.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                bookingEndPropertyChange(evt);
            }
        });
        getContentPane().add(bookingEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 133, -1));

        bookingDay.setEditable(false);
        getContentPane().add(bookingDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 133, -1));

        jLabel10.setText("Days of Stay:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 80, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Booking Form");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 24, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hotel2.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 250, 140));

        jButton2.setText("Book");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, -1, -1));

        bookingBack.setText("Cancel");
        bookingBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingBackActionPerformed(evt);
            }
        });
        getContentPane().add(bookingBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, 40, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 51));
        jLabel14.setText("Record doesn't Exist !");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, -1));

        bookingGet.setText("Get Days");
        bookingGet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingGetActionPerformed(evt);
            }
        });
        getContentPane().add(bookingGet, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 51));
        jLabel15.setText("Please fill in both of the date!");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 51));
        jLabel16.setText("Press me to get Days!");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookingBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingBackActionPerformed
        //to available room page
        availableroom obj1 = new availableroom();
        obj1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bookingBackActionPerformed

    private void bookingFillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingFillActionPerformed
        try {
            //retrieve data from customer.txt if ic_number variable match the ic columns in customer.txt
            String ic_number = String.valueOf(bookingIc.getSelectedItem());
            
            client client1 = new client(ic_number);
            String res = client1.getCustomerBookingData();
            
            if(res == "Success"){
                jLabel14.setVisible(false);
                String[] myBookingData = client.myBookingData;
                bookingName.setText(myBookingData[0]);
                bookingEmail.setText(myBookingData[1]);
                bookingContact.setText(myBookingData[2]);
            }
            else {
                jLabel14.setVisible(true);
            }
        } catch (IOException ex) {
            Logger.getLogger(bookingform.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_bookingFillActionPerformed

    private void bookingEndMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingEndMouseExited

    }//GEN-LAST:event_bookingEndMouseExited

    private void bookingEndPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_bookingEndPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingEndPropertyChange

    private void bookingEndFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bookingEndFocusLost

    }//GEN-LAST:event_bookingEndFocusLost

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded

    }//GEN-LAST:event_formComponentAdded

    private void bookingGetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingGetActionPerformed
    try{
        //minus between dates
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Date firstDate = bookingStart.getDate();
        Date secondDate = bookingEnd.getDate();
        LocalDate localFirstDate = LocalDate.ofInstant(firstDate.toInstant(), ZoneId.systemDefault());
        LocalDate localSecondDate = LocalDate.ofInstant(secondDate.toInstant(), ZoneId.systemDefault());

        long daysBetween = ChronoUnit.DAYS.between(localFirstDate, localSecondDate);
        jLabel15.setVisible(false);
        
        String days = String.valueOf(daysBetween);
        
        bookingDay.setText(days);
        }
    catch(Exception e){
        jLabel15.setVisible(true);
    }
    
    }//GEN-LAST:event_bookingGetActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //booking and writing record into booking.txt
        
        String roomid, roomlevel, roomsize, customeric, customername, customercontact, customeremail, day, formattedStart, formattedEnd;
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        roomid = bookingID.getText();
        roomlevel = bookingLevel.getText();
        roomsize = bookingSize.getText();
        customeric = String.valueOf(bookingIc.getSelectedItem());
        customername = bookingName.getText();
        customercontact = bookingContact.getText();
        customeremail = bookingEmail.getText();
        formattedStart = dateFormat.format(bookingStart.getDate());
        formattedEnd = dateFormat.format(bookingEnd.getDate());
        day = bookingDay.getText();
        
        if(bookingDay.getText().isEmpty()){
            jLabel16.setVisible(true);
        }else{
            jLabel16.setVisible(false);
            booking obj1 = new booking(roomid, roomlevel, roomsize, customeric, customername, customeremail, customercontact, formattedStart, formattedEnd, day);
            String res = obj1.writeBooking();
            if(res == "Success"){
                menu a = new menu();
                a.setVisible(true);
                this.setVisible(false);
            }else{
                 JOptionPane.showMessageDialog(null,"Booking Failed Please try again!","Failed",JOptionPane.INFORMATION_MESSAGE);
                 availableroom b = new availableroom();
                 b.setVisible(true);
                 this.setVisible(false);
            }
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookingform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookingform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookingform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookingform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new bookingform().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(bookingform.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookingBack;
    private javax.swing.JTextField bookingContact;
    private javax.swing.JTextField bookingDay;
    private javax.swing.JTextField bookingEmail;
    private com.toedter.calendar.JDateChooser bookingEnd;
    private javax.swing.JButton bookingFill;
    private javax.swing.JButton bookingGet;
    private javax.swing.JTextField bookingID;
    private javax.swing.JComboBox<String> bookingIc;
    private javax.swing.JTextField bookingLevel;
    private javax.swing.JTextField bookingName;
    private javax.swing.JTextField bookingSize;
    private com.toedter.calendar.JDateChooser bookingStart;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
