/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

import java.io.File;
import java.io.IOException;
import java.io.RandomAccessFile;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author user
 */
public class history extends javax.swing.JFrame {

    /**
     * Creates new form history
     */
    public history() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        historySearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        historyTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("History");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 80, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Search: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        historySearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historySearchActionPerformed(evt);
            }
        });
        historySearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                historySearchKeyReleased(evt);
            }
        });
        getContentPane().add(historySearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 480, -1));

        String[] COLUMN_NAMES = {"Room ID", "Level", "Size", "IC/Passport", "Name", "Email", "Contact", "Start Date", "End Date", "Day of Stay", "Checkin", "Checkout", "Total Paid"};
        DefaultTableModel model = new DefaultTableModel(COLUMN_NAMES, 0);

        // Open the History.txt file as a RandomAccessFile for reading
        try (RandomAccessFile raf = new RandomAccessFile(new File("History.txt"), "r")) {
            // Read each line from the file and add it as a row to the table model
            String line;
            while ((line = raf.readLine()) != null) {
                String[] data = new String[13];
                data[0] = line.substring(9); // Room ID
                line = raf.readLine();
                data[1] = line.substring(12); // Level
                line = raf.readLine();
                data[2] = line.substring(11); // Size
                line = raf.readLine();
                data[3] = line.substring(13); // IC/Passport
                line = raf.readLine();
                data[4] = line.substring(6); // Name
                line = raf.readLine();
                data[5] = line.substring(7); // Email
                line = raf.readLine();
                data[6] = line.substring(9); // Contact
                line = raf.readLine();
                data[7] = line.substring(12); // Start Date
                line = raf.readLine();
                data[8] = line.substring(10); // End Date
                line = raf.readLine();
                data[9] = line.substring(14); // Day of Stay
                line = raf.readLine();
                data[10] = line.substring(10); // Checkin
                line = raf.readLine();
                data[11] = line.substring(11); // Checkout
                line = raf.readLine();
                data[12] = line.substring(12); // Total Paid
                line = raf.readLine();
                model.addRow(data);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        historyTable.setModel(model);
        jScrollPane1.setViewportView(historyTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 130, 950, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //navigate to menu
        menu a = new menu();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void historySearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historySearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_historySearchActionPerformed

    private void historySearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_historySearchKeyReleased
        //filtering the history jtable
        DefaultTableModel obj = (DefaultTableModel) historyTable.getModel();
        TableRowSorter<DefaultTableModel> obj1 = new TableRowSorter<>(obj);
        historyTable.setRowSorter(obj1);
        obj1.setRowFilter(RowFilter.regexFilter(historySearch.getText()));
    }//GEN-LAST:event_historySearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new history().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField historySearch;
    private javax.swing.JTable historyTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
