/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;

/**
 *
 * @author user
 */
public class loading extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form loading
     */
    public loading() {
        initComponents();
        //creating other threads
        Thread t = new Thread(this);
        t.start();
    }
    
    @Override
    public void run() {
        //make loading bar run to 100
        for (int i = 1; i <= 100; i++){
            try{ 
                Thread.sleep(20);
            }
            catch (Exception e){
                e.printStackTrace();
            }
            loadingCount.setText(i + "%");
            loadingBar.setValue(i);
        }

        login a = new login();
        a.setVisible(true);
        this.setVisible(false);
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadingBackground = new javax.swing.JLabel();
        loadingIcon = new javax.swing.JLabel();
        loadingBar = new javax.swing.JProgressBar();
        loadingCount = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loadingBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.png"))); // NOI18N
        getContentPane().add(loadingBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 62, -1, 234));

        loadingIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        getContentPane().add(loadingIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 13, -1, -1));

        loadingBar.setBackground(new java.awt.Color(255, 255, 255));
        loadingBar.setToolTipText("");
        loadingBar.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        getContentPane().add(loadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 345, 476, 6));

        loadingCount.setText("100 %");
        getContentPane().add(loadingCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 320, 37, 18));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Loading...");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 321, 63, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loading().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel loadingBackground;
    private javax.swing.JProgressBar loadingBar;
    private javax.swing.JLabel loadingCount;
    private javax.swing.JLabel loadingIcon;
    // End of variables declaration//GEN-END:variables


}
