/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginTitle = new javax.swing.JLabel();
        loginDivider = new javax.swing.JSeparator();
        loginPicture = new javax.swing.JLabel();
        loginEmail = new javax.swing.JTextField();
        loginLabelEmail = new javax.swing.JLabel();
        loginLabelPassword = new javax.swing.JLabel();
        loginLogin = new javax.swing.JButton();
        loginPassword = new javax.swing.JPasswordField();
        loginRegister = new javax.swing.JButton();
        loginForget = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        loginTitle.setText("Login");
        getContentPane().add(loginTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 13, -1, -1));

        loginDivider.setBackground(new java.awt.Color(0, 0, 0));
        loginDivider.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(loginDivider, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 13, 16, 274));

        loginPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hotel.jpg"))); // NOI18N
        loginPicture.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(loginPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 30, 301, 228));
        getContentPane().add(loginEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 96, 195, -1));

        loginLabelEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loginLabelEmail.setText("Email :");
        getContentPane().add(loginLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 96, 51, -1));

        loginLabelPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loginLabelPassword.setText("Password : ");
        getContentPane().add(loginLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 156, -1, -1));

        loginLogin.setText("Login");
        loginLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginLoginActionPerformed(evt);
            }
        });
        getContentPane().add(loginLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 250, 80, -1));
        getContentPane().add(loginPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 156, 195, -1));

        loginRegister.setText("Register");
        loginRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(loginRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 250, -1, -1));

        loginForget.setText("Forget Password");
        loginForget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginForgetActionPerformed(evt);
            }
        });
        getContentPane().add(loginForget, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 250, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginLoginActionPerformed
        //check whether the login credentials are similar or not
        String email = loginEmail.getText();
        String password = loginPassword.getText();
        
        staff obj1 = new staff(email, password);
        
        try {
            String res=obj1.login();
            if(res == "Success"){
                menu a = new menu();
                a.setVisible(true);
                this.setVisible(false);
                obj1.mySession();
            }
            else if (res == "Fail"){
                JOptionPane.showMessageDialog(null, "Invalid Credentials!","Error",JOptionPane.ERROR_MESSAGE);
            }
            
            
        } catch (IOException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
        

        
        
    }//GEN-LAST:event_loginLoginActionPerformed

    private void loginForgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginForgetActionPerformed
        //navigate to forgetpassword
        
        forgetpassword a = new forgetpassword();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_loginForgetActionPerformed

    private void loginRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginRegisterActionPerformed
        //navigate to register
        
        register a = new register();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_loginRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator loginDivider;
    private javax.swing.JTextField loginEmail;
    private javax.swing.JButton loginForget;
    private javax.swing.JLabel loginLabelEmail;
    private javax.swing.JLabel loginLabelPassword;
    private javax.swing.JButton loginLogin;
    private javax.swing.JPasswordField loginPassword;
    private javax.swing.JLabel loginPicture;
    private javax.swing.JButton loginRegister;
    private javax.swing.JLabel loginTitle;
    // End of variables declaration//GEN-END:variables
}
