/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

/**
 *
 * @author user
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuProfile = new javax.swing.JButton();
        menuTopic = new javax.swing.JLabel();
        menuAvailable = new javax.swing.JButton();
        menuCustomer = new javax.swing.JButton();
        menuBooked = new javax.swing.JButton();
        menuLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profileicon.png"))); // NOI18N
        menuProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProfileActionPerformed(evt);
            }
        });
        getContentPane().add(menuProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 72, 175, 125));

        menuTopic.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuTopic.setText("Menu");
        getContentPane().add(menuTopic, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 22, -1, -1));

        menuAvailable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bookingicon.png"))); // NOI18N
        menuAvailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAvailableActionPerformed(evt);
            }
        });
        getContentPane().add(menuAvailable, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 72, 175, 125));

        menuCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/customericon.png"))); // NOI18N
        menuCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCustomerActionPerformed(evt);
            }
        });
        getContentPane().add(menuCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 288, 175, 125));

        menuBooked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bookroomicon.png"))); // NOI18N
        menuBooked.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBookedActionPerformed(evt);
            }
        });
        getContentPane().add(menuBooked, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 288, 175, 125));

        menuLogout.setText("Logout");
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(menuLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 25, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Booking");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 431, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Profile");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Customer");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 431, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Available Rooms");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 210, -1, -1));

        jButton1.setText("History");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProfileActionPerformed
        //navigtae to modify profile page
        modifyprofile a = new modifyprofile();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuProfileActionPerformed

    private void menuBookedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBookedActionPerformed
        //navigate to mybooking page
        mybooking a = new mybooking();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuBookedActionPerformed

    private void menuAvailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAvailableActionPerformed
        //navigate to available room page
        availableroom a = new availableroom();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuAvailableActionPerformed

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        //navigate to login page (logout)
        login a = new login();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuLogoutActionPerformed

    private void menuCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCustomerActionPerformed
        //navigate to customer page
        customer a = new customer();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuCustomerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        history a = new history();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton menuAvailable;
    private javax.swing.JButton menuBooked;
    private javax.swing.JButton menuCustomer;
    private javax.swing.JButton menuLogout;
    private javax.swing.JButton menuProfile;
    private javax.swing.JLabel menuTopic;
    // End of variables declaration//GEN-END:variables
}
