/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class modifybooking extends javax.swing.JFrame {

    /**
     * Creates new form modifybooking
     */
    public modifybooking() throws ParseException {
        initComponents();
        //get array data from booking
        String[] modifybooking = booking.modifybooking;
        
        //display data in text field
        modifyid.setText(modifybooking[0]);
        modifyic.setText(modifybooking[1]);
        modifyname.setText(modifybooking[2]);
        
        //date conversion
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        
        Date date1 = dateFormat.parse(modifybooking[3]);
        Date date2 = dateFormat.parse(modifybooking[4]);
        modifystart.setDate(date1);
        modifyend.setDate(date2);
        
        modifyday.setText(modifybooking[5]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        modifyid = new javax.swing.JTextField();
        modifyic = new javax.swing.JTextField();
        modifyname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        modifystart = new com.toedter.calendar.JDateChooser();
        modifyend = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        modifyday = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Modify Booking");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 13, -1, -1));

        modifyid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyidActionPerformed(evt);
            }
        });
        getContentPane().add(modifyid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 160, -1));

        modifyic.setEditable(false);
        getContentPane().add(modifyic, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 160, -1));

        modifyname.setEditable(false);
        getContentPane().add(modifyname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 160, -1));

        jLabel2.setText("Room ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 70, 53, -1));

        jLabel3.setText("Customer IC/Passport:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel4.setText("Customer Name:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 90, -1));
        getContentPane().add(modifystart, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 140, -1));
        getContentPane().add(modifyend, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 140, -1));

        jLabel5.setText("Start Date:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));

        jLabel6.setText("End Date:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, -1));

        modifyday.setEditable(false);
        getContentPane().add(modifyday, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 140, -1));

        jLabel7.setText("Days:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));

        jButton1.setText("Get Day");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));

        jButton2.setText("Complete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modifyidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyidActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //get difference between dates
        Date start = modifystart.getDate();
        Date end = modifyend.getDate();
        
        long diffInMilliseconds = end.getTime() - start.getTime();
        long diffInDays = TimeUnit.MILLISECONDS.toDays(diffInMilliseconds);
        String daysAsString = String.valueOf(diffInDays);
        
        modifyday.setText(daysAsString);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            //modification of booking information
            String id = modifyid.getText();
            String ic = modifyic.getText();
            String name = modifyname.getText();
            String day = modifyday.getText();
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            String startDateString = dateFormat.format(modifystart.getDate());
            String endDateString = dateFormat.format(modifyend.getDate());
            
            booking obj1 = new booking(id, ic, name, startDateString, endDateString, day);
            String res = obj1.editrecord();
            
            if(res == "Success"){
                JOptionPane.showMessageDialog(null,"Modify Success!","Edit",JOptionPane.INFORMATION_MESSAGE);
                mybooking a = new mybooking();
                a.setVisible(true);
                this.setVisible(false);
            }
            
        } catch (IOException ex) {
            Logger.getLogger(modifybooking.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modifybooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modifybooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modifybooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modifybooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new modifybooking().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(modifybooking.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField modifyday;
    private com.toedter.calendar.JDateChooser modifyend;
    private javax.swing.JTextField modifyic;
    private javax.swing.JTextField modifyid;
    private javax.swing.JTextField modifyname;
    private com.toedter.calendar.JDateChooser modifystart;
    // End of variables declaration//GEN-END:variables
}
