/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

import java.awt.print.PrinterJob;
import javax.print.PrintService;
import javax.print.PrintException;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.standard.MediaPrintableArea;
import java.awt.*;
import java.awt.print.PrinterException;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.text.JTextComponent;
/**
 *
 * @author user
 */
public class receipt extends javax.swing.JFrame {

    /**
     * Creates new form receipt
     */
    public receipt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        receipt = new javax.swing.JTextArea();
        printButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        receiptgenerate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Receipt");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        receipt.setColumns(20);
        receipt.setRows(5);
        jScrollPane1.setViewportView(receipt);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 220, 410));

        printButton.setText("Print");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });
        getContentPane().add(printButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, -1, -1));

        jButton2.setText("Complete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 510, -1, -1));

        receiptgenerate.setText("Generate");
        receiptgenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiptgenerateActionPerformed(evt);
            }
        });
        getContentPane().add(receiptgenerate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        //printing receipt
        JTextComponent textComponent = receipt;

        try {
            textComponent.print(); // Print the contents of the text field
        } catch (PrinterException ex) {
            // Handle any printing exceptions
            JOptionPane.showMessageDialog(this, "Printing failed: " + ex.getMessage(), "Printing Error", JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_printButtonActionPerformed

    private void receiptgenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiptgenerateActionPerformed
        //get array date from booking
        String[] historydata = booking.historydata;
        
        System.out.println(historydata[9]);
        
        //conversion to double value
        String dayString = historydata[9];
        double day = Double.parseDouble(dayString);
        
        //total day price
        double totalday = day * 350;
        //service tax
        double servicetax = totalday * 0.1;
        //tourism tax
        double tourismtax = day * 10;
        //total amount to be paid
        double total = totalday + servicetax + tourismtax;
        

        String totalpaid = String.valueOf(total);
        
        historydata[12] = totalpaid; 
        
        
        // Create the date format
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");

        // Get the current date and time
        Date currentDate = new Date();

        // Format the date as a string
        String currentDateTime = dateFormat.format(currentDate);
        
        StringBuilder receiptText = new StringBuilder();
            
        receiptText.append("Hotel Wise Receipt\n\n");
        
        receiptText.append("--------------------------------------\n");
        
        receiptText.append("Customer Name: " + historydata[4] + "\n");
        
        receiptText.append("Date: " + currentDateTime + "\n");
        
        receiptText.append("--------------------------------------\n");
        
        receiptText.append("Checked In: "+ historydata[10] +"\n");
        
        receiptText.append("Checked Out: " + historydata[11] + "\n");
        
        receiptText.append("--------------------------------------\n\n");
        
        receiptText.append("Room ID: " + historydata[0] + "\n\n");
        
        receiptText.append("Days of Stay: "+ historydata[9] + " * 350 = "+ totalday  + "\n");
        
        receiptText.append("Service Tax: "+ totalday + " * 0.1 = "+ servicetax  + "\n");
        
        receiptText.append("Tourism Tax: "+ historydata[9] + " * 10 = "+ tourismtax + "\n\n");
        
        receiptText.append("---------------------------------------\n");
        
        receiptText.append("Total: RM "+ total + "\n");
        
        receiptText.append("---------------------------------------\n");

        receipt.setText(receiptText.toString());
    }//GEN-LAST:event_receiptgenerateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            String[] historydata = booking.historydata;
            
            //delete the record from booking after completed the check out action
            
            booking obj1 = new booking(historydata[0], historydata[3]);
            obj1.writeHistory();
            
            String res = obj1.deleterecord();
            
            if(res == "Success"){
                mybooking a = new mybooking();
                a.setVisible(true);
                this.setVisible(false);
            }
            
        } catch (IOException ex) {
            Logger.getLogger(receipt.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new receipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton printButton;
    private javax.swing.JTextArea receipt;
    private javax.swing.JButton receiptgenerate;
    // End of variables declaration//GEN-END:variables
}
