/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

import static assignment.staff.countlines;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        registerName = new javax.swing.JTextField();
        registerEmail = new javax.swing.JTextField();
        registerPassword = new javax.swing.JPasswordField();
        registerPassword2 = new javax.swing.JPasswordField();
        registerSecurity = new javax.swing.JTextField();
        registerReset = new javax.swing.JButton();
        registerRegister = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        registerBack = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Registration Form");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 13, -1, -1));

        jLabel2.setText("Username:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 72, -1, -1));

        jLabel3.setText("Email:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 132, 37, -1));

        jLabel4.setText("Password:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 192, 55, -1));

        jLabel5.setText("Confirm Password:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 250, -1, -1));

        jLabel6.setText("Security Code:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 304, -1, -1));
        getContentPane().add(registerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 69, 266, -1));
        getContentPane().add(registerEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 129, 266, -1));
        getContentPane().add(registerPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 189, 266, -1));
        getContentPane().add(registerPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 247, 203, -1));
        getContentPane().add(registerSecurity, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 301, 203, -1));

        registerReset.setText("Reset");
        registerReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerResetActionPerformed(evt);
            }
        });
        getContentPane().add(registerReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 369, -1, -1));

        registerRegister.setText("Register");
        registerRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(registerRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 369, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 51));
        jLabel7.setText("Username can't contain Integer / Special Character!");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 76, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Invalid Email!");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 136, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Password should be more than 6 characters  and must with upper + lower case!");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 196, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Security code should contain at least 5 characters!");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 308, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 51));
        jLabel11.setText("Password does not match!");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 254, -1, -1));

        registerBack.setText("Back");
        registerBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBackActionPerformed(evt);
            }
        });
        getContentPane().add(registerBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 369, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 51));
        jLabel12.setText("Password and Security Code can't be the same!");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 341, 243, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerResetActionPerformed
       //reset all field
        registerEmail.setText("");
        registerPassword.setText("");
        registerPassword2.setText("");
        registerSecurity.setText("");
        registerName.setText("");
    }//GEN-LAST:event_registerResetActionPerformed

    private void registerRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerRegisterActionPerformed

        try {
            //registering an admin
            String username, email, password1, password2, security, date;
            boolean isUsername = false, isEmail = false, isPassword = false, samePassword = false, isSecurity = false, checkName = false, checkEmail = false, checkSecurity = false;
            username = registerName.getText();
            email = registerEmail.getText();
            password1 = registerPassword.getText();
            password2 = registerPassword2.getText();
            security = registerSecurity.getText();
            String pattern = ".*[!@#$%^&*()\\-_=+\\[\\]{};:\'\"<>,./?\\\\|`~].*";
            
            String myusername, myemail, mypassword, mysecurity, mydate, myspace;
            
            RandomAccessFile raf = new RandomAccessFile("Login.txt", "rw");
            
            for(int i=1; i < countlines() ; i++){
                
                myusername = raf.readLine().substring(10);
                myemail = raf.readLine().substring(7);
                mypassword = raf.readLine().substring(10);
                mysecurity = raf.readLine().substring(10);
                mydate =raf.readLine().substring(15);
                myspace =raf.readLine().substring(0);
                                 
                    //check duplicated username
                    if(myusername.equals(username)){
                        JOptionPane.showMessageDialog(null,"Username is taken please use another username!","Error",JOptionPane.INFORMATION_MESSAGE);
                        registerName.setText("");
                    } else {
                        checkName = true;
                    }
                    
                    //check duplicated email
                    if(myemail.equals(email)){
                        JOptionPane.showMessageDialog(null,"Email is registered please use another email!","Error",JOptionPane.INFORMATION_MESSAGE);
                        registerEmail.setText("");
                    } else {
                        checkEmail= true;
                    }
            }
                    //check if both password are same
                    if(password1.equals(security)){
                        jLabel12.setVisible(true);
                        registerSecurity.setText("");
                    } else{
                        checkSecurity = true;
                        jLabel12.setVisible(false);
                    }
                    
                    //username validation
                    if (username.length() < 2 || username.isEmpty()){
                        jLabel7.setVisible(true);
                    } else if (username.matches(".*\\d+.*")|| username.matches(pattern)){
                        jLabel7.setVisible(true);
                    } else{
                        isUsername = true;
                        jLabel7.setVisible(false);
                    }
                    
                    //email validation
                    if ((email == null || email.isEmpty())){
                        jLabel8.setVisible(true);
                    } else if (!email.contains("@") || (!email.contains(".com"))){
                        jLabel8.setVisible(true);
                    } else{
                        isEmail = true;
                        jLabel8.setVisible(false);
                    }
                    
                    //password validation
                    if ( password1.isEmpty()) {
                        jLabel9.setVisible(true);
                    }else if (password1.length() < 6){
                        jLabel9.setVisible(true);
                    }else if (!password1.matches(".*[A-Z].*") || !password1.matches(".*[a-z].*")){
                        jLabel9.setVisible(true);
                    }else{
                        isPassword = true;
                        jLabel9.setVisible(false);
                    }
                    
                    //security code validation
                    if (security.isEmpty()) {
                        jLabel10.setVisible(true);
                    }else if (security.length() < 5){
                        jLabel10.setVisible(true);
                    }else{
                        isSecurity = true;
                        jLabel10.setVisible(false);
                    }
                    
                    //password similarities with confirm password
                    if(password2.equals(password1)){
                        samePassword = true;
                        jLabel11.setVisible(false);
                    } else{
                        jLabel11.setVisible(true);
                    }  
                    
                    SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
                    
                    
                    //creating current date
                    Date currentDate = new Date();
                    date = formatter.format(currentDate);
                    
                    if (isUsername && isEmail && isPassword && samePassword && isSecurity && checkName && checkEmail && checkSecurity){
                        staff obj1 = new staff(username, email, password1, security, date);
                       
                        String res=obj1.writeRecord();
                        
                        if(res == "Success"){
                            JOptionPane.showMessageDialog(null,"Registration completed.","Success",JOptionPane.INFORMATION_MESSAGE);
                            login a = new login();
                            a.setVisible(true);
                            this.setVisible(false);
                        }else
                            JOptionPane.showMessageDialog(null, "Please try again! Something happened","Error",JOptionPane.ERROR_MESSAGE);
                    }  
                    
                       
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
        }     

    }//GEN-LAST:event_registerRegisterActionPerformed

        
    private void registerBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBackActionPerformed
        login a = new login();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_registerBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new register().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton registerBack;
    private javax.swing.JTextField registerEmail;
    private javax.swing.JTextField registerName;
    private javax.swing.JPasswordField registerPassword;
    private javax.swing.JPasswordField registerPassword2;
    private javax.swing.JButton registerRegister;
    private javax.swing.JButton registerReset;
    private javax.swing.JTextField registerSecurity;
    // End of variables declaration//GEN-END:variables
}
